# Generated by Django 4.0.4 on 2022-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.CharField(choices=[('1', 'University'), ('2', 'Study'), ('3', 'Self education'), ('4', 'Other charge')], max_length=20)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
