# Generated by Django 4.0.4 on 2022-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.CharField(choices=[('Important', 'Important'), ('Normal', 'Normal'), ('Not big deal', 'Not big deal')], max_length=100)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('University', 'University'), ('Study', 'Study'), ('Self education', 'Self education'), ('Other charge', 'Other charge')], max_length=20)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
